name: Anime Episode Notifier

on:
  workflow_dispatch:

  schedule:
    - cron: '30 * * * *'

concurrency:
  group: discord-notifier-state
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  notify-anime:
    name: Check anime episodes

    runs-on: ubuntu-latest

    env:
      ANIME_SCHEDULE_TOKEN: ${{ secrets.ANIME_SCHEDULE_TOKEN }}
      DISCORD_ANIME_WEBHOOK_URL: ${{ secrets.DISCORD_ANIME_WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Check anime episodes
        run: npm run anime:start

      - name: Save anime notification state
        shell: bash
        run: |
          if git diff --quiet -- data/sent-anime.json; then
            echo "Nenhuma alteração no estado dos animes."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/sent-anime.json
          git commit -m "chore: update sent anime state"

          echo "Sincronizando com a branch remota..."

          git pull --rebase origin main

          git push origin HEAD:main
